Vagrant.configure("2") do |config|
  # Настройки для всех машин
  config.vm.box = "ubuntu/focal64"
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible/site.yml"
    ansible.config_file = "ansible/ansible.cfg"
    ansible.inventory_path = "ansible/inventory/hosts.yml"
    ansible.verbose = "v"
  end

  # База данных
  config.vm.define "db1" do |db|
    db.vm.hostname = "db1"
    db.vm.network "private_network", ip: "192.168.56.11"
    db.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
  end

  # Веб-сервер
  config.vm.define "web1" do |web|
    web.vm.hostname = "web1"
    web.vm.network "private_network", ip: "192.168.56.12"
    web.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
  end
end