# -*- mode: ruby -*-
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"

  config.vm.boot_timeout = 800

  config.vm.define "server" do |s|
    s.vm.hostname = "server"
    s.vm.network "private_network", ip: "192.168.56.11"
    s.vm.provision "shell", path: "scripts/openvpn-server.sh"

    s.vm.provision "shell", inline: <<-SHELL
          iptables -A INPUT -p icmp -j DROP
          echo "✅ ICMP заблокирован"
        SHELL
  end

  config.vm.define "client" do |c|
    c.vm.hostname = "client"
    c.vm.network "private_network", ip: "192.168.56.10"
    c.vm.provision "shell", path: "scripts/openvpn-client.sh"

    c.vm.provision "shell", inline: <<-SHELL
          # Добавить ограничение в SSH конфиг
          if ! grep -q "AllowUsers vagrant@192.168.56.11" /etc/ssh/sshd_config; then
            echo "AllowUsers vagrant@192.168.56.11" >> /etc/ssh/sshd_config
          fi

          # Перезапустить SSH
          systemctl restart sshd

          # Дополнительно: iptables для гарантии
          iptables -A INPUT -p tcp -s 192.168.56.11 --dport 22 -j ACCEPT
          iptables -A INPUT -p tcp --dport 22 -j DROP

          echo "✅ SSH разрешён только с 192.168.56.11"
        SHELL
  end
end