apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wordpress-stack.fullname" . }}-db-credentials
  labels:
    {{- include "wordpress-stack.labels" . | nindent 4 }}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.credentials.rootPassword | b64enc | quote }}
  MYSQL_PASSWORD: {{ .Values.mysql.credentials.password | b64enc | quote }}